name: notify-new-release

on:
  release:
    types: [published]

jobs:
  sending-email:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Send email
        uses: dawidd6/action-send-mail@v3.6.1
        with:
          server_address: smtp.gu.se
          server_port: 993
          username: ${{secrets.EMAIL_PW}}
          password: ${{secrets.EMAIL_UNAME}}
          subject: Message from github actions.
          to: anders.lind.cgg@gu.se,anders.e.lind@vgregion.se
          from: Anders Lind <anders.lind.cgg@gu.se>
          secure: true
          body: workflow for ${{github.repository}} completed successfully!
	  